version: "3.2"
services:
  wildfly:
    build:
      context: docker_dir
      dockerfile: ./Dockerfile
    ports:
      - 8085:8080
      - 9992:9990
    entrypoint: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
    networks:
      - backend
    depends_on:
      - db
    restart: always

  db:
    image: mysql
    environment:
      MYSQL_USER: tijesunimi
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: testea
    ports:
      - 3309:3306
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend


  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080
    networks:
      - backend
    depends_on:
      - db

volumes:
  dbdata:

networks:
  backend: